# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)' 
    includeRootFolder: true 
    archiveType: 'zip' 
    # Options: zip, 7z, tar, wim
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    #replaceExistingArchive: true 
    #verbose: # Optional
    #quiet: # Optional    

#- task: SnykSecurityScan@1
#  inputs:
#    serviceConnectionEndpoint: 'testmavenSnyk'
#    testType: 'app'
#    monitorWhen: 'always'
#    failOnIssues: true
#    projectName: 'MavenSnykDemo-13/12/2021'

- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    FodConnection: 'FoD'
    ReleaseOptions: '0'
    ReleaseId: 167905
    EntitlementSelection: '1'
    EntitlementPreference: '2'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'mvn'
    PolicyFailAction: '0'